package ca.sfu.cmpt276.be.parentapp.controller;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.TypeAdapter;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.time.LocalDateTime;
import java.util.ArrayList;

import ca.sfu.cmpt276.be.parentapp.model.Child;
import ca.sfu.cmpt276.be.parentapp.model.Coin;
import ca.sfu.cmpt276.be.parentapp.model.Task;

/**
 * DataManager is a singleton that holds onto persistent data in the app such the list of Child and
 * the history of Coinflips. It also serializes this data into JSON.
 */
public class DataManager {
    public static final String CHILDREN_SAVENAME = "JsonChildren";
    public static final String COINFLIP_SAVENAME = "JsonCoinflip";
    public static final String CHILD_INDEX_SAVENAME = "JsonChildIndex";
    private static final String TASK_SAVENAME = "JsonTasks";
    private static DataManager instance;

    private ArrayList<Child> childList = new ArrayList<>();
    private ArrayList<Coin> coinFlipHistory = new ArrayList<>();
    private ArrayList<Task> taskList = new ArrayList<>();
    private int childFlipIndex = 0;

    private SaveManager saveOption;

    /**
     * SaveManager allows flexibility in the saving functionality of the app by allowing the JSON
     * strings generated by DataManager to be implemented by the client in the way they see fit.
     */
    public interface SaveManager {

        String load(String saveName);
        void save(String saveJson, String saveName);
    }
    public static DataManager getInstance() {
        if (instance == null) {
            instance = new DataManager();
        }
        return instance;
    }
    private DataManager() {}

    public void setSaveOption(SaveManager saveInterface) {
        saveOption = saveInterface;
    }

    //Source: Dr. Victor Cheung, CMPT213 Fall 2021, Assignment 1.
    private static class LocalDateTimeJSONReader extends TypeAdapter<LocalDateTime> {

        @Override
        public void write(JsonWriter jsonWriter,
                          LocalDateTime localDateTime) throws IOException {
            jsonWriter.value(localDateTime.toString());
        }

        @Override
        public LocalDateTime read(JsonReader jsonReader) throws IOException {
            return LocalDateTime.parse(jsonReader.nextString());
        }

    }
    public void deserializeData() {
        Gson gson = new GsonBuilder()
                .registerTypeAdapter(LocalDateTime.class, new LocalDateTimeJSONReader() {})
                .create();

        String jsonChildren = saveOption.load(CHILDREN_SAVENAME);
        if (!jsonChildren.isEmpty()) {
            childList = gson.fromJson(jsonChildren, new TypeToken<ArrayList<Child>>(){}.getType());
        }

        String jsonCoinflip = saveOption.load(COINFLIP_SAVENAME);
        if (!jsonCoinflip.isEmpty()) {
            coinFlipHistory = gson.fromJson(jsonCoinflip, new TypeToken<ArrayList<Coin>>(){}.getType());
        }
        String jsonChildIndex = saveOption.load(CHILD_INDEX_SAVENAME);
        if (!jsonChildIndex.isEmpty()) {
            childFlipIndex = Integer.parseInt(jsonChildIndex);
        }

        String jsonTasks = saveOption.load(TASK_SAVENAME);
        if (!jsonTasks.isEmpty()) {
            taskList = gson.fromJson(jsonTasks, new TypeToken<ArrayList<Task>>(){}.getType());
        }
    }
    public void serializeChildren() {
        Gson gson = new GsonBuilder()
                .create();
        String gsonChildren = gson.toJson(childList);
        saveOption.save(CHILDREN_SAVENAME, gsonChildren);
    }

    public void serializeCoinflips() {
        Gson gson = new GsonBuilder()
                .registerTypeAdapter(LocalDateTime.class, new LocalDateTimeJSONReader() {})
                .create();
        String gsonCoinflip = gson.toJson(coinFlipHistory);
        saveOption.save(COINFLIP_SAVENAME, gsonCoinflip);
        saveOption.save(CHILD_INDEX_SAVENAME, Integer.toString(childFlipIndex));
    }

    public void serializeTasks() {
        Gson gson = new GsonBuilder()
                .create();
        String gsonTasks = gson.toJson(taskList);
        saveOption.save(TASK_SAVENAME, gsonTasks);
    }

    public ArrayList<Child> getChildList() {
        return childList;
    }

    public ArrayList<Coin> getCoinFlipHistory() {
        return coinFlipHistory;
    }

    public Integer getChildFlipIndex() {
        return childFlipIndex;
    }

    public ArrayList<Task> getTaskList() {
        return taskList;
    }

    public void setChildFlipIndex(int set) {
        childFlipIndex = set;
    }
}
