package ca.sfu.cmpt276.be.parentapp.view;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.view.MenuItem;

import androidx.appcompat.app.AppCompatActivity;
import androidx.cardview.widget.CardView;

import ca.sfu.cmpt276.be.parentapp.R;
import ca.sfu.cmpt276.be.parentapp.controller.DataManager;

/**
 * MainActivity in the starting screen of the app with buttons leading to each feature. It also
 * implements the SaveManager to save the Json strings generated by DataManager to its own
 * Shared Preferences.
 */
public class MainActivity extends AppCompatActivity {
    public static final String PREF_SAVE_NAME = "SaveData";
    SharedPreferences saveSP;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        setUpSaving();
        loadData();
        setUpChildButton();
        setUpTimeoutButton();
        setUpTaskButton();
        setUpHelpButton();
        setUpBreathButton();
    }

    public static void navigate(Context context, MenuItem menuItem, int current) {
        int id = menuItem.getItemId();
        if (id == current) {
            return;
        }
        Activity currentActivity = (Activity) context;

        switch (id) {
            case (R.id.item_breath):
                currentActivity.startActivity(new Intent(context, BreathActivity.class));
                break;
            case (R.id.item_timeout):
                currentActivity.startActivity(new Intent(context, TimeoutActivity.class));
                break;
            case (R.id.item_tasks):
                currentActivity.startActivity(new Intent(context, TaskListActivity.class));
                break;
            case (R.id.item_coinflip):
                currentActivity.startActivity(new Intent(context, CoinFlipActivity.class));
                break;
            case (R.id.item_child):
                currentActivity.startActivity(new Intent(context, ChildListActivity.class));
                break;
        }
        currentActivity.overridePendingTransition(0, 0);
        currentActivity.finish();
    }

    private void setUpHelpButton() {
        CardView button_help = findViewById(R.id.button_help);
        button_help.setOnClickListener(view -> {
            Intent helpActivity = HelpActivity.makeIntent(MainActivity.this);
            startActivity(helpActivity);
        });
    }

    private void setUpTaskButton() {
        CardView toTasks = findViewById(R.id.button_task_list);
        toTasks.setOnClickListener(view -> {
            Intent tasksActivity = new Intent(getApplicationContext(), TaskListActivity.class);
            startActivity(tasksActivity);
        });
    }

    private void setUpTimeoutButton() {
        CardView button_timeout = findViewById(R.id.button_timeout);
        button_timeout.setOnClickListener(view -> {
            Intent timeoutActivity = TimeoutActivity.makeIntent(MainActivity.this);
            startActivity(timeoutActivity);
        });
    }

    private void setUpChildButton() {
        CardView toChildren = findViewById(R.id.button_children);
        toChildren.setOnClickListener(v -> {
            Intent childActivity = ChildListActivity.makeIntent(MainActivity.this);
            startActivity(childActivity);
        });

        CardView button2 = findViewById(R.id.button_coin_flip);

        button2.setOnClickListener(v -> {
            Intent intent = new Intent(getApplicationContext(), CoinFlipActivity.class);
            startActivity(intent);
        });
    }

    private void setUpBreathButton() {
        CardView toBreath = findViewById(R.id.button_breath);
        toBreath.setOnClickListener(v -> {
            Intent breathActivity = new Intent(getApplicationContext(), BreathActivity.class);
            startActivity(breathActivity);
        });

        CardView button2 = findViewById(R.id.button_coin_flip);

        button2.setOnClickListener(v -> {
            Intent intent = new Intent(getApplicationContext(), CoinFlipActivity.class);
            startActivity(intent);
        });
    }

    private void setUpSaving() {
        DataManager dataManager = DataManager.getInstance();
        dataManager.setSaveOption(new DataManager.SaveManager() {
            @Override
            public String load(String saveName) {
                saveSP = getApplicationContext().getSharedPreferences(PREF_SAVE_NAME, Context.MODE_PRIVATE);
                return saveSP.getString(saveName, "");
            }

            @Override
            public void save(String saveName, String saveJson) {
                saveSP = getApplicationContext().getSharedPreferences(PREF_SAVE_NAME, Context.MODE_PRIVATE);
                SharedPreferences.Editor editor = saveSP.edit();
                editor.putString(saveName, saveJson);
                editor.apply();
            }
        });
    }




    private void loadData() {
        DataManager.getInstance().deserializeData();
    }
}