package ca.sfu.cmpt276.be.parentapp.view;

import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.widget.Button;

import androidx.appcompat.app.AppCompatActivity;

import ca.sfu.cmpt276.be.parentapp.R;
import ca.sfu.cmpt276.be.parentapp.TaskListActivity;
import ca.sfu.cmpt276.be.parentapp.controller.DataManager;

/**
 * MainActivity in the starting screen of the app with buttons leading to each feature. It also
 * implements the SaveManager to save the Json strings generated by DataManager to its own
 * Shared Preferences.
 */
public class MainActivity extends AppCompatActivity {
    public static final String SP_SAVE_NAME = "SaveData";
    SharedPreferences saveSP;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        setUpSaving();
        loadData();
        setUpChildButton();
        setUpTimeoutButton();
        setUpTaskButton();
    }

    private void setUpTaskButton() {
        Button toTasks = findViewById(R.id.task_list_button);
        toTasks.setOnClickListener(view -> {
            Intent tasksActivity = new Intent(getApplicationContext(), TaskListActivity.class);
            startActivity(tasksActivity);
        });
    }

    private void setUpTimeoutButton() {
        Button button_timeout = findViewById(R.id.timeout_button);
        button_timeout.setOnClickListener(view -> {
            Intent timeoutActivity = TimeoutActivity.makeIntent(MainActivity.this);
            startActivity(timeoutActivity);
        });
    }

    private void setUpChildButton() {
        Button toChildren = findViewById(R.id.children_button);
        toChildren.setOnClickListener(v -> {
            Intent childActivity = ChildListActivity.makeIntent(MainActivity.this);
            startActivity(childActivity);
        });

        Button button2 = findViewById(R.id.coin_flip_button);

        button2.setOnClickListener(v -> {
            Intent intent = new Intent(getApplicationContext(), CoinFlipActivity.class);
            startActivity(intent);
        });
    }

    private void setUpSaving() {
        DataManager dataManager = DataManager.getInstance();
        dataManager.setSaveOption(new DataManager.SaveManager() {
            @Override
            public String load(String saveName) {
                saveSP = getApplicationContext().getSharedPreferences(SP_SAVE_NAME, Context.MODE_PRIVATE);
                return saveSP.getString(saveName, "");
            }

            @Override
            public void save(String saveName, String saveJson) {
                saveSP = getApplicationContext().getSharedPreferences(SP_SAVE_NAME, Context.MODE_PRIVATE);
                SharedPreferences.Editor editor = saveSP.edit();
                editor.putString(saveName, saveJson);
                editor.apply();
            }
        });
    }

    private void loadData() {
        DataManager.getInstance().deserializeData();
    }
}